-- Migration 014: Create Coach Observations System
-- Stores AI-detected patterns for proactive coaching

CREATE TABLE IF NOT EXISTS coach_observations (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  observation_type TEXT NOT NULL CHECK (observation_type IN ('pattern', 'concern', 'win', 'correlation', 'stuck')),
  content TEXT NOT NULL,
  data_summary JSONB NOT NULL,
  priority TEXT NOT NULL CHECK (priority IN ('low', 'medium', 'high')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  surfaced_at TIMESTAMPTZ,
  user_response TEXT,
  dismissed BOOLEAN DEFAULT FALSE
);

-- Add indexes
CREATE INDEX IF NOT EXISTS idx_coach_observations_user ON coach_observations(user_id);
CREATE INDEX IF NOT EXISTS idx_coach_observations_type ON coach_observations(observation_type);
CREATE INDEX IF NOT EXISTS idx_coach_observations_priority ON coach_observations(priority);
CREATE INDEX IF NOT EXISTS idx_coach_observations_surfaced ON coach_observations(surfaced_at) WHERE surfaced_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_coach_observations_dismissed ON coach_observations(dismissed) WHERE dismissed = FALSE;

-- Composite index for querying unsurfaced high-priority observations
CREATE INDEX IF NOT EXISTS idx_coach_observations_pending
ON coach_observations(user_id, priority, created_at)
WHERE surfaced_at IS NULL AND dismissed = FALSE;

-- Add comments
COMMENT ON TABLE coach_observations IS 'AI-detected patterns and insights generated by daily cron job. Surfaced contextually during conversations.';
COMMENT ON COLUMN coach_observations.observation_type IS 'Type of observation: pattern (recurring behavior), concern (risk), win (achievement), correlation (relationship between domains), stuck (blocked progress)';
COMMENT ON COLUMN coach_observations.content IS 'Human-readable observation text surfaced to user (e.g., "You have 3 Body tasks stuck in progress for over a week")';
COMMENT ON COLUMN coach_observations.data_summary IS 'JSON data supporting the observation (e.g., {"task_ids": [...], "stuck_days": [...]})';
COMMENT ON COLUMN coach_observations.priority IS 'Priority level: high (surface if inactive 3+ days), medium (7+ days), low (only if contextually relevant)';
COMMENT ON COLUMN coach_observations.surfaced_at IS 'Timestamp when observation was shown to user in conversation';
COMMENT ON COLUMN coach_observations.user_response IS 'User response or action taken after seeing observation';
COMMENT ON COLUMN coach_observations.dismissed IS 'Whether user dismissed the observation';

-- Enable RLS
ALTER TABLE coach_observations ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Users can view own observations" ON coach_observations
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can update own observations" ON coach_observations
  FOR UPDATE USING (auth.uid() = user_id);

-- System can insert observations (via service role)
-- No policy needed as worker uses admin client

-- Verification
SELECT 'Coach observations table created' AS status;
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_name = 'coach_observations'
ORDER BY ordinal_position;
